### ISSUE TITLE
newbie trying to use jpiv

### ISSUE THREAD

**Issue by tritoniadiomedea** [eguvep/jpiv#2]
Anyone willing to help a biologist?  I opened & selected my 650 image sequence, set settings to analyze sequential files (1-2, 2-3, 3-4, etc) then ran PIV image analysis.  No output but I have this error.  Sorry, but the code is all greek to me.  Should I retreat, or might there be some simple fix?

JPIV 2020.04.26
Copyright (C) 2020 Peter Vennemann
JPIV is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.
See http://www.gnu.org/licenses/ for details.
Can not find a user settings file. 
You are probably using JPIV the first time. 
A default settings file is created in your home directory.
Session started by jamesmurray on 10.4.2021 at 15:56
No files selected.
JPiv PIV evaluation started.
Available cores: 8
Using 2 cores.
Processing: t-tetra-pt67x-r-higher 001
Exception in thread "Thread-3" java.lang.IllegalAccessError: class javax.media.jai.RasterAccessor (in unnamed module @0x4ccc0db7) cannot access class sun.awt.image.BytePackedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x4ccc0db7
	at javax.media.jai.RasterAccessor.<init>(RasterAccessor.java:802)
	at com.sun.media.jai.opimage.CopyOpImage.computeRect(CopyOpImage.java:68)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:969)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at com.sun.media.jai.opimage.CropOpImage.getTile(CropOpImage.java:122)
	at com.sun.media.jai.opimage.TranslateIntOpImage.getTile(TranslateIntOpImage.java:132)
	at javax.media.jai.PlanarImage.cobbleUShort(PlanarImage.java:3052)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2175)
	at javax.media.jai.UntiledOpImage.computeTile(UntiledOpImage.java:212)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:750)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:750)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at javax.media.jai.UntiledOpImage.computeTile(UntiledOpImage.java:212)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at com.sun.media.jai.opimage.TranslateIntOpImage.getTile(TranslateIntOpImage.java:132)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at com.sun.media.jai.opimage.PeriodicShiftOpImage.computeTile(PeriodicShiftOpImage.java:118)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:911)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.copyData(PlanarImage.java:2343)
	at javax.media.jai.RenderedOp.copyData(RenderedOp.java:2299)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2525)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2546)
	at jpiv2.PivEvaluation$AddCorrelation.run(PivEvaluation.java:450)
Exception in thread "Thread-2" java.lang.IllegalAccessError: class javax.media.jai.RasterAccessor (in unnamed module @0x4ccc0db7) cannot access class sun.awt.image.BytePackedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x4ccc0db7
	at javax.media.jai.RasterAccessor.<init>(RasterAccessor.java:802)
	at com.sun.media.jai.opimage.CopyOpImage.computeRect(CopyOpImage.java:68)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:969)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at com.sun.media.jai.opimage.CropOpImage.getTile(CropOpImage.java:122)
	at com.sun.media.jai.opimage.TranslateIntOpImage.getTile(TranslateIntOpImage.java:132)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at javax.media.jai.UntiledOpImage.computeTile(UntiledOpImage.java:212)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:750)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:750)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at javax.media.jai.UntiledOpImage.computeTile(UntiledOpImage.java:212)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at com.sun.media.jai.opimage.TranslateIntOpImage.getTile(TranslateIntOpImage.java:132)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at com.sun.media.jai.opimage.PeriodicShiftOpImage.computeTile(PeriodicShiftOpImage.java:118)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:911)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.copyData(PlanarImage.java:2343)
	at javax.media.jai.RenderedOp.copyData(RenderedOp.java:2299)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2525)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2546)
	at jpiv2.PivEvaluation$AddCorrelation.run(PivEvaluation.java:450)

**Comment by eguvep** [comment]
Dear @tritoniadiomedea, 
it looks like there is a missing library. Did you try a fresh install of the Java Runtime Environment (JRE)?
Regards!
Peter

**Comment by eguvep** [comment]
I assume a fresh install worked out?
